name: tmdb
description: "Favorite movies app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  flutter_svg: ^2.2.3
  shared_preferences: ^2.3.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^4.0.0
  build_runner: ^2.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: 
  riverpod_lint: 

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  riverpod_generator: 4.0.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/images/Loader.svg
    - assets/images/StarOn.svg
    - assets/images/StarOff.svg
    - assets/images/Search.svg
    - assets/images/NotFound.svg
    - assets/images/Sun.svg
    - assets/images/Moon.svg
    - assets/images/Left.svg
    